# Generated by Django 5.1.6 on 2025-02-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20)),
                ('gos_num', models.CharField(max_length=10)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZakazNaryad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remont', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('predoplata', models.IntegerField(default=0)),
                ('avans', models.IntegerField(default=0)),
                ('raskhod', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('auto', models.ForeignKey(blank=True, default='Без номера', on_delete=django.db.models.deletion.PROTECT, to='kuzov.auto')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kuzov.client')),
                ('master', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naryads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
