# Generated by Django 4.2.1 on 2025-02-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZakazNaryad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remont', models.TextField(blank=True, max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('auto', models.ForeignKey(blank=True, default='Без номера', on_delete=django.db.models.deletion.PROTECT, to='kuzov.auto')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='kuzov.client')),
            ],
        ),
    ]
