# Generated by Django 5.2.1 on 2025-07-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kuzov', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznaryad',
            name='master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naryads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raskhod',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raskhod', to='kuzov.zakaznaryad'),
        ),
        migrations.AddField(
            model_name='oplata',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplata', to='kuzov.zakaznaryad'),
        ),
        migrations.AddField(
            model_name='avans',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avans', to='kuzov.zakaznaryad'),
        ),
    ]
