# Generated by Django 5.2.1 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raskhod',
            name='cheque',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cheques/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='raskhod',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='raskhod',
            name='name',
            field=models.CharField(default='расходник'),
        ),
    ]
