# Generated by Django 5.1.6 on 2025-03-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0002_remove_zakaznaryad_predoplata_oplata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaznaryad',
            name='avans',
        ),
        migrations.RemoveField(
            model_name='zakaznaryad',
            name='raskhod',
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avans', to='kuzov.zakaznaryad')),
            ],
        ),
        migrations.CreateModel(
            name='Raskhod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raskhod', to='kuzov.zakaznaryad')),
            ],
        ),
    ]
