# Generated by Django 5.1.6 on 2025-03-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0003_remove_zakaznaryad_avans_remove_zakaznaryad_raskhod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznaryad',
            name='in_work',
            field=models.BooleanField(choices=[(False, 'Закрыт'), (True, 'Открыт')], default=1, verbose_name='Статус'),
        ),
    ]
