# Generated by Django 4.2.1 on 2025-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0004_avans_cashier_oplata_cashier_raskhod_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='raskhod',
            name='spare_part',
            field=models.BooleanField(default=False, verbose_name='Запчасть, оплачивает клиент'),
        ),
    ]
