# Generated by Django 5.2.1 on 2025-07-23 13:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0004_zakaznaryad_in_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaznaryad',
            options={'verbose_name': 'Заказ-наряд', 'verbose_name_plural': 'Заказ-наряды'},
        ),
        migrations.AddField(
            model_name='auto',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер в формате: '+79999999999'", regex='^\\+?[78]\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='zakaznaryad',
            name='master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naryads', to=settings.AUTH_USER_MODEL, verbose_name='master'),
        ),
    ]
