# Generated by Django 5.2.1 on 2025-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0005_raskhod_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='avans',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='oplata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
