# Generated by Django 5.2.1 on 2025-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzov', '0006_avans_date_oplata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='avans',
            name='comment',
            field=models.CharField(blank=True),
        ),
    ]
