# Generated by Django 5.2.1 on 2026-02-22 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Базовая стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalculationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.carmodel', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Сессия расчета',
                'verbose_name_plural': 'Сессии расчетов',
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(choices=[('front_left', 'Спереди слева'), ('rear_right', 'Сзади справа')], max_length=20, verbose_name='Код проекции')),
                ('image', models.ImageField(upload_to='calculator/projections/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='calculator.carmodel', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Проекция',
                'verbose_name_plural': 'Проекции',
                'ordering': ['order'],
                'unique_together': {('car_model', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название детали')),
                ('coordinates', models.TextField(help_text='SVG path или координаты полигона (например: "M10,10 L20,20 L30,10 Z")', verbose_name='Координаты контура')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='calculator.projection', verbose_name='Проекция')),
            ],
            options={
                'verbose_name': 'Деталь кузова',
                'verbose_name_plural': 'Детали кузова',
                'ordering': ['projection', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SelectedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.bodypart', verbose_name='Деталь')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_parts', to='calculator.calculationsession', verbose_name='Сессия')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Выбранная деталь',
                'verbose_name_plural': 'Выбранные детали',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'part')},
            },
        ),
    ]
