# Generated by Django 5.2.1 on 2026-02-23 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_services', to='calculator.bodypart', verbose_name='Деталь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_services', to='calculator.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга для детали',
                'verbose_name_plural': 'Услуги для деталей',
                'ordering': ['part', 'service'],
                'unique_together': {('part', 'service')},
            },
        ),
    ]
