# Generated by Django 5.2.1 on 2026-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_partservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='rgba(40, 167, 69, 0.2)', help_text='Формат: rgba(255, 0, 0, 0.3) или #RRGGBB', max_length=50, verbose_name='Цвет заливки'),
        ),
    ]
