# Generated by Django 5.2.1 on 2026-02-27 03:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название детали')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Деталь кузова',
                'verbose_name_plural': 'Детали кузова',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('background_image', models.ImageField(help_text='Изображение, которое будет фоном при выборе категории', upload_to='works/categories/', verbose_name='Фоновое изображение')),
                ('icon', models.CharField(default='fa-wrench', help_text='Например: fa-paint-roller, fa-wrench, fa-car', max_length=50, verbose_name='Иконка Font Awesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена от')),
                ('description', models.CharField(blank=True, help_text='Например: "с подготовкой" или "под ключ"', max_length=200, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='works.bodypart', verbose_name='Деталь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='works.workcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
                'ordering': ['category', 'order', 'part'],
                'unique_together': {('category', 'part')},
            },
        ),
    ]
